### ISSUE TITLE
query_diet is "less reliable" with ETag caching 

### ISSUE THREAD

**Issue by makmic** [makandra/query_diet#35]
This might rather be an oddity than an actual bug. I just noticed locally that the query_diet widget does not reflect the fact that part of my application was served based on the ETag caching mechanism. The application used less queries to render my page - so a lower number within the widget is perfectly fine.

However, I do not always _actively_ think about ETags when looking at the widgets. Often I just use it to decide whether I should investigate the query usage or not.. 

A solution would be to extend the existing widget with a small warning if parts of the page were served using the browser cache. WDYT?

---

While typing down this proposal I started wondering about a second thing: If `render_query_diet` is rendered on a ETag-cached site, how can we sure that it is being constantly updated? :thinking:

**Comment by kratob** [comment]
I *think* this is probably out of scope.

So, in a classic setup (i.e. no JavaScript frameworks), there is little we can do. Either the page is served from the browser cache (and then it will naturally show the query count from the  cached request, since the query count itself is cached), or it isn't. We could theoretically somehow try to run some JavaScript and detect that we are currently showing a "stale" response, but I'm not sure how that even helps.

I suspect your usecase makes more sense when used together with a framework like Unpoly, where parts of the page are served via different html fragments, some of which might be cached. But here, only the framework could be aware of this. Query_diet only embeds the query count into these html fragments. The query count most likely only reflects one of your fragments anyways, there is no logic that somehow sums queries.

Does this make sense, or am I missing something here?

**Comment by makmic** [comment]
Ok! It's probably easier to update our mental model of "what does query_diet tell me exactly?" than to alter the widget itself.
